/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DenimwearRouteImport } from './routes/denimwear'
import { Route as KnitwearRouteImport } from './routes/knitwear'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SportswearRouteImport } from './routes/sportswear'
import { Route as WovenwearRouteImport } from './routes/wovenwear'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DenimwearRoute = DenimwearRouteImport.update({
  id: '/denimwear',
  path: '/denimwear',
  getParentRoute: () => rootRouteImport,
} as any)
const KnitwearRoute = KnitwearRouteImport.update({
  id: '/knitwear',
  path: '/knitwear',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SportswearRoute = SportswearRouteImport.update({
  id: '/sportswear',
  path: '/sportswear',
  getParentRoute: () => rootRouteImport,
} as any)
const WovenwearRoute = WovenwearRouteImport.update({
  id: '/wovenwear',
  path: '/wovenwear',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/denimwear': typeof DenimwearRoute
  '/knitwear': typeof KnitwearRoute
  '/products': typeof ProductsRoute
  '/sportswear': typeof SportswearRoute
  '/wovenwear': typeof WovenwearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/denimwear': typeof DenimwearRoute
  '/knitwear': typeof KnitwearRoute
  '/products': typeof ProductsRoute
  '/sportswear': typeof SportswearRoute
  '/wovenwear': typeof WovenwearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/denimwear': typeof DenimwearRoute
  '/knitwear': typeof KnitwearRoute
  '/products': typeof ProductsRoute
  '/sportswear': typeof SportswearRoute
  '/wovenwear': typeof WovenwearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/denimwear'
    | '/knitwear'
    | '/products'
    | '/sportswear'
    | '/wovenwear'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/denimwear'
    | '/knitwear'
    | '/products'
    | '/sportswear'
    | '/wovenwear'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/denimwear'
    | '/knitwear'
    | '/products'
    | '/sportswear'
    | '/wovenwear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DenimwearRoute: typeof DenimwearRoute
  KnitwearRoute: typeof KnitwearRoute
  ProductsRoute: typeof ProductsRoute
  SportswearRoute: typeof SportswearRoute
  WovenwearRoute: typeof WovenwearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denimwear': {
      id: '/denimwear'
      path: '/denimwear'
      fullPath: '/denimwear'
      preLoaderRoute: typeof DenimwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knitwear': {
      id: '/knitwear'
      path: '/knitwear'
      fullPath: '/knitwear'
      preLoaderRoute: typeof KnitwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportswear': {
      id: '/sportswear'
      path: '/sportswear'
      fullPath: '/sportswear'
      preLoaderRoute: typeof SportswearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wovenwear': {
      id: '/wovenwear'
      path: '/wovenwear'
      fullPath: '/wovenwear'
      preLoaderRoute: typeof WovenwearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DenimwearRoute: DenimwearRoute,
  KnitwearRoute: KnitwearRoute,
  ProductsRoute: ProductsRoute,
  SportswearRoute: SportswearRoute,
  WovenwearRoute: WovenwearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
